apiVersion: v1
kind: Service
metadata:
  name: mongodb
  Namespace: roboshop
spec:
  selector: #paina vuna pod create ipothadi service dheniki velli attach avvali that is the service.
    app: mongodb # has to match .spec.selector.matchLabels
    project: roboshop
    tier: db
  clusterIP: None
  ports:
    - protocol: TCP
      port: 27017 #service port we can give anything
      targetPort: 27017 #containerPort  , nginx