# apiVersion: v1
# kind: Service
# metadata:
#   name: redis
#   Namespace: roboshop
# spec:
#   type: LoadBalancer
#   selector: #paina vuna pod create ipothadi service dheniki velli attach avvali that is the service.
#     app: redis # has to match .spec.selector.matchLabels
#     project: roboshop
#     tier: db
#   ports:
#   - protocol: TCP
#     port: 80 #service port we can give anything
#     targetPort: 80 #containerPort  , nginx
#   clusterIP: None
#   selector:
#     app: redis
#     project: roboshop
#     tier: db

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379
  clusterIP: None
  selector:
    app: redis
    project: roboshop
    tier: db