apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  Namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: redis 
      project: roboshop
      tier: db
  serviceName: redis
  replicas: {{ .Values.statefulset.replicas }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: redis 
        project: roboshop
        tier: db  
    spec:
      containers:
      - name: redis
        image: "redis"
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi