apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector: #paina vuna pod create ipothadi service dheniki velli attach avvali that is the service.
    app: cart
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service port we can give anything
    targetPort: 8080 #containerPort  , nginx