apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  Namespace: roboshop
  labels:
    app: rabbitmq
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: rabbitmq 
      project: roboshop
      tier: db
  serviceName: rabbitmq
  replicas: {{ .Values.statefulset.replicas }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: rabbitmq 
        project: roboshop
        tier: db  
    spec:
      containers:
      - name: rabbitmq
        image: "charankumarpadeti/rabbitmq:{{ .Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: rabbitmq
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi